# Generated by Django 5.1.3 on 2024-11-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_chat_title_remove_user_tg_id_chat_admins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='bot_is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
