# Generated by Django 5.1.3 on 2024-11-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_chat_id_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userschats',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='userschats',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
