# Generated by Django 5.1.3 on 2024-12-01 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_chat_admins_userschats_is_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
